
/control/verbose 2
/control/saveHistory
/run/verbose 2

#detectors and components
#/lmon/construct/geometry view_side.xml
#/lmon/construct/geometry view_front.xml
#/lmon/construct/geometry view_top.xml
/lmon/construct/geometry view_cell.xml

# Initialize kernel
/run/initialize

/vis/open OGL 800x600-0+0
#/vis/open OGL 1000x1000-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/viewer/set/background 1 1 1 0.
#/vis/viewer/set/lightsThetaPhi 120. 135. deg
#
# Draw geometry:
/vis/drawVolume

#front view
#/vis/viewer/set/viewpointThetaPhi 0 0 deg
#/vis/viewer/set/lightsThetaPhi 90 45 deg

#side view
/vis/viewer/set/viewpointThetaPhi -90 0 deg
/vis/viewer/set/lightsThetaPhi -45 -45 deg

#top view -90 -90
#/vis/viewer/set/viewpointThetaPhi -90 -89.999999 deg
#/vis/viewer/set/lightsThetaPhi 90 45 deg

#/vis/viewer/set/targetPoint 0 100 -250 mm
#/vis/viewer/set/targetPoint 0 0 0 mm

# Specify zoom value:
#/vis/viewer/zoom 2.

# Draw coordinate axes:
#/vis/scene/add/axes 185 10 12 10. mm
#/vis/scene/add/axes 0 8 10 10 mm
#/vis/scene/add/axes 0 0 0 153 mm
#/vis/scene/add/axes -1 -2 2.26795 1.732 mm

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/scene/add/trajectories rich
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/modeling/trajectories/drawByCharge-0/default/setLineWidth 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

#set the gui
/control/execute ../gui.mac

































