
#detector
#/lmon/construct/geometry geom_qcal2.xml
/lmon/construct/geometry geom_qcal2_etag.xml

#input
/lmon/input/type gun
/gun/energy 1 GeV
#/gun/particle e-
/gun/particle gamma
/gun/position 0 0 1 mm
/gun/direction 0 0 -1

#output
#/lmon/output/name qcal2.root

#initialize and run
/run/initialize

#/process/optical/boundary/setInvokeSD true

#/process/optical/cerenkov/verbose 2
#/process/optical/scintillation/verbose 2
#/process/optical/verbose 2

/run/beamOn 1

